<?php
/** @var $block Magento\Framework\View\Element\Template */
/** @var $messageViewModel Techdriven\MagentoJsFun\ViewModel\Message */
$messageViewModel = $block->getData('message_view_model');
?>
<div id="vue-test">
    <h1>{{ message }}</h1>
</div>

<script type="text/x-magento-init">
    {
        "#vue-test": {
            "Techdriven_MagentoJsFun/js/vue-test": {
                "message": "<?= $messageViewModel->getMessage(); ?>"
            }
        }
    }
</script>
